name: CI

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build for Windows
      run: |
        cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CPACK_PACKAGE_FILE_NAME=windows-latest
        cmake --build build --target package
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-latest
        path: build/windows-latest.zip

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build for Ubuntu
      run: |
        cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_FLAGS="-O2 -flto" -D CPACK_PACKAGE_FILE_NAME=linux-latest
        cmake --build build --target package
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-latest
        path: build/linux-latest.zip

  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build for macOS
      run: |
        cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_FLAGS="-O2 -flto" -D CPACK_PACKAGE_FILE_NAME=darwin-latest
        cmake --build build --target package
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: darwin-latest
        path: build/darwin-latest.zip

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: [build-windows, build-ubuntu, build-macos]

    steps:
    - name: Download win artifact
      uses: actions/download-artifact@v1
      with:
        name: windows-latest
    - name: Download linux artifact
      uses: actions/download-artifact@v1
      with:
        name: linux-latest
    - name: Download darwin artifact
      uses: actions/download-artifact@v1
      with:
        name: darwin-latest
    - name: Upload to S3
      run: |
          echo "Not doing anything yet!"