name: CI

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build for Windows
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl duality.c /O2
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: duality.exe

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build for Ubuntu
      run: gcc duality.c -O2 -o duality
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: duality

  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build for macOS
      run: clang duality.c -O2 -o duality
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: duality

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: [build-windows, build-ubuntu, build-macos]

    steps:
    - name: Download win artifact
      uses: actions/download-artifact@v1
      with:
        name: windows
    - name: Download linux artifact
      uses: actions/download-artifact@v1
      with:
        name: linux
    - name: Download macOS artifact
      uses: actions/download-artifact@v1
      with:
        name: macos
    - name: Upload to S3
      run: |
        aws s3 cp windows/duality.exe s3://duality-releases/windows/duality.exe --region us-east-1 --output text --acl public-read
        aws s3 cp linux/duality s3://duality-releases/linux/duality --region us-east-1 --output text --acl public-read
        aws s3 cp macos/duality s3://duality-releases/macos/duality --region us-east-1 --output text --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}